import Head from 'next/head'
import Image from 'next/image'
import { useAtom } from "jotai";
import { userAtom } from 'store';
import styles from "styles/Home.module.css";
import PropertyCard from '../components/PropertyCard/PropertyCard'
import APIManager from './api/axiosMethods'

export default function Home() {

  const handleRegister = async () => {
      const userPayload = { "user": {
      "email": "test3@yopmail.com",
      "password": "azerty"
    }};
    await APIManager.register(userPayload);
  }
  const handleLogin = async () => {
      const userPayload = { "user": {
      "email": "test3@yopmail.com",
      "password": "azerty"
    }};
    await APIManager.logIn(userPayload);
  }

  const handleDisconnect = async () => {
    await APIManager.logOut();
  }

  const [user] = useAtom(userAtom);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Salut {user?.email ?? "étranger"} !
        </h1>

        <PropertyCard description={"WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA WOH SUPER MAISON LA "}/>
      </main>
    </div>
  )
}
